# Note - see README.md for fuller explanation of each parameter

# Data Preprocessing
data_path: ./data/imputed_scania.csv.gz
unit_identifier: vehicle_id
time_identifier: time_step
target_feature: in_study_repair
test_size: 0.15
seed: 42
lag_length: 0
sampling_n: 5

# ML Model Training
hyperoptimize: false
n_trials: 30
