# Note - see README.md for fuller explanation of each parameter

# Train or predict mode
mode: train

# General data settings, pertain to train or predict mode
data:
  data_path: ../data/train_scania.csv.gz
  unit_identifier: vehicle_id
  time_identifier: time_step
  target_feature: in_study_repair
  lag_length: 1
  sampling_n: 3

# Training only settings
training_config:
  test_size: 0.15
  hyperoptimize: false
  n_trials: 30
  save_model: true

# Predict only settings
predict_config:
  model_path: <file>.zip

seed: 42

hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}